In [ ]:
# ((k+2)n-kn)/2

sides = 4
dimensions = 3
((sides+2)**dimensions - sides**dimensions)/2

In [ ]:

(sides**dimensions - (sides-1)^dimensions)

In [ ]:
n=2
n*3**(n-1)

In [ ]:
(5**dimensions - 3**dimensions)/2.

In [ ]:
from itertools import combinations, permutations
from typing import List
import numpy as np

board_size = 5
board_dimensions = 4
check_sum = ((board_size + 2) ** board_dimensions - board_size**board_dimensions) // 2

array = np.arange(board_size**board_dimensions).reshape(
    board_size, *([board_size] * (board_dimensions - 1))
)


def reshape(array: np.ndarray, size: int = board_size):
    reshape = np.prod(array.shape) // (size)
    result = array.reshape(reshape, size)
    return result

def generate_diagonals(array: np.ndarray) -> np.ndarray:
    result = []
    board = array.copy()
    axes = list(permutations(range(len(array.shape)), 2))
    while axes:      
        diagonals = reshape(np.diagonal(board))
        result.extend(diagonals.tolist())
        if len(diagonals) == board_size:            
            diagonals = generate_diagonals(np.array(diagonals))
            result.extend(diagonals)
        array = np.rot90(board, axes=axes.pop())

    return result # type: ignore

result = []
board = array.copy()
axes = list(permutations(range(board_dimensions), 2))
while axes:
    result.extend(reshape(board).tolist())    
    diags = generate_diagonals(board)
    result.extend(diags)
    board = np.rot90(array, axes=axes.pop())



print(f"{array=}")

result = set(tuple(sorted(item)) for item in result)

print(result)
print(f"{check_sum == len(result)}, {check_sum = }, {len(result) = }")

In [ ]:
print(np.array([0, 4, 8]).shape)
print(np.array([[0, 4, 8]]).shape)

In [ ]:
from itertools import combinations, permutations
from typing import List
import numpy as np

board_size = 3
board_dimensions = 3
check_sum = ((board_size + 2) ** board_dimensions - board_size**board_dimensions) // 2

array = np.arange(board_size**board_dimensions).reshape(
    board_size, *([board_size] * (board_dimensions - 1))
)

print(array, sep="\n")

In [21]:
print(array)
print()


def reshape(array: np.ndarray, size: int = board_size):
    reshape = np.prod(array.shape) // (size)
    result = array.reshape(reshape, size)
    return result


def generate_diagonals(array: np.ndarray) -> np.ndarray:
    result = []
    diags = []
    axes = list(permutations(range(len(array.shape)), 2))
    while axes:
        axis = axes.pop()
        tmp = array.copy()
        while True:
            diags.extend(reshape(np.diagonal(tmp)).tolist())
            result.extend(diags)
            if len(diags) == board_size:
                diags.extend(reshape(np.diagonal(diags)).tolist())
                result.extend(diags)
            tmp = np.rot90(tmp, axes=axis)
            if np.array_equal(tmp, array):
                break
                
            
    tmp = set(tuple(sorted(item)) for item in diags)
    print(f"{tmp=}")
    return result # type: ignore


result = []
axes = list(combinations(range(board_dimensions), 2))
while axes:
    axis = axes.pop()
    print(axis)
    tmp = array.copy()
    print(tmp)
    while True:
        result.extend(reshape(tmp).tolist())
        result.extend(generate_diagonals(tmp))
        tmp = np.rot90(tmp, axes=axis)
        if np.array_equal(tmp, array):
            break

result = set(tuple(sorted(item)) for item in result)

print(f"{check_sum == len(result)}, {check_sum = }, {len(result) = }")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

(1, 2)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
tmp={(0, 4, 8), (11, 13, 15), (0, 13, 26), (2, 10, 18), (0, 12, 24), (6, 16, 26), (9, 13, 17), (0, 10, 20), (1, 13, 25), (6, 12, 18), (2, 14, 26), (5, 13, 21), (8, 16, 24), (3, 13, 23), (8, 14, 20), (7, 13, 19), (18, 22, 26), (2, 4, 6), (20, 22, 24)}
tmp={(0, 4, 8), (11, 13, 15), (2, 10, 18), (0, 12, 24), (6, 16, 26), (9, 13, 17), (0, 10, 20), (1, 13, 25), (6, 12, 18), (2, 14, 26), (8, 16, 24), (5, 13, 21), (3, 13, 23), (8, 14, 20), (2, 13, 24), (7, 13, 19), (18, 22, 26), (2, 4, 6), (20, 22, 24)}
tmp={(0, 4, 8), (11, 13, 15), (2, 10, 18), (0, 12, 24), (6, 16, 26), (9, 13, 17), (0, 10, 20), (1, 13, 25), (6, 12, 18), (2, 14, 26), (5, 13, 21), (8, 16, 24), (3, 13, 23), (8, 14, 20), (8, 13, 18), (7, 13, 19), (18, 22, 26), (2, 4, 6), (20, 22

In [ ]:

data = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 20, 30], [40, 50, 60], [70, 80, 90]]], [[[100, 200, 300], [400, 500, 600], [700, 800, 900]], [[1000, 2000, 3000], [4000, 5000, 6000], [7000, 8000, 9000]]]])

print(data)
print(data.reshape(-1, 3))
print(data.reshape(-1, 3).tolist())
print(data.reshape(-1, 2).tolist())

In [5]:
tuple(set(range(3**2)) ^ {5, 4, 6})

(0, 1, 2, 3, 7, 8)

In [4]:
import requests
response = requests.get("https://itunes.apple.com/search?entity=song&limit=1&term=")

In [8]:
length = 2
def get_expected(length: int, inception: int):
    if inception == 0:
        return tuple(range(length))
    
    return {key: get_expected(length, inception - 1) for key in range(length)}    

get_expected(4,2)

{0: {0: (0, 1, 2, 3), 1: (0, 1, 2, 3), 2: (0, 1, 2, 3), 3: (0, 1, 2, 3)},
 1: {0: (0, 1, 2, 3), 1: (0, 1, 2, 3), 2: (0, 1, 2, 3), 3: (0, 1, 2, 3)},
 2: {0: (0, 1, 2, 3), 1: (0, 1, 2, 3), 2: (0, 1, 2, 3), 3: (0, 1, 2, 3)},
 3: {0: (0, 1, 2, 3), 1: (0, 1, 2, 3), 2: (0, 1, 2, 3), 3: (0, 1, 2, 3)}}

In [27]:
import csv
import os
from tabulate import tabulate
print(os.getcwd())
with open("test.csv") as csvfile:
        reader:csv.DictReader = csv.DictReader(csvfile)
        print(type(reader.fieldnames))
        table = tabulate(reader,headers=reader.fieldnames,tablefmt="grid")
        print(table)

/home/thenin/mine/3843209/cs50p
<class 'list'>


ValueError: headers for a list of dicts is not a dict or a keyword

In [30]:
a=1
b=-11
if (a+b) =< a:
    print("Nope!")

SyntaxError: invalid syntax (154917893.py, line 3)

In [48]:
class Something:
    def __init__(self, name: str = "Groot") -> None:
        self._name = name

    @property
    def name(self) -> str:
        return self._name


    def hi(self) -> None:
        return f"I am {self._name}..."

In [50]:
groot = Something()
groot.name = "not a groot"  # there is no setter
print(groot.hi())

AttributeError: property 'name' of 'Something' object has no setter

In [52]:
groot = Something()
groot._name = "not a groot" # but I do not really need it ;)
print(groot.hi())

I am not a groot...


In [54]:
raise ValueError("test")

ValueError: test